apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: vlados135/vladnginx:main
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 82
        - containerPort: 83
        volumeMounts:
        - mountPath: /etc/nginx/sites-enabled
          name: default
        - mountPath: /var/log
          name: logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: pvc
      - name: default
        configMap:
          name: default