apiVersion: v1
kind: ConfigMap
metadata:
  name: default
data:
  default: |
    server {
    listen 80 default_server;

    root /var/www/html;


    index index.html;

    server_name server;
    
    location /clown.jpg {
        proxy_pass http://localhost:81;
    }

    location /sh-boom.mp3 {
    add_header Content-disposition "attachment; filename=$1";
    default_type application/octet-stream;
    proxy_pass http://localhost:82;                
    }
    
    location /redirect {
    return 301 http://www.google.com;
    }
    }

    server {
    listen 81;
    root /var/www/html/img;
    index indeximg.html;
    server_name imageserver;
    }

    server {
    listen 82;
    root /var/www/html/mus;
    index indexmus.html;
    server_name musicserver;
    }
